services:
  postgres:
    image: postgres:17-alpine
    container_name: snippetbox_pg
    ports:
      - 5432:5432
    volumes:
      - /home/gerben/data/pg_data/snippetbox:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=sb-user
      - POSTGRES_DB=sb-database
      - PGDATA=/var/lib/postgresql/data/pgdata # Add this line
    restart: always
