apiVersion: v1
kind: PersistentVolume
metadata:
  name: sb-app-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    # - nfsvers=3 # Try NFSv3 instead of 4.1
    - hard
    - timeo=600
    - retrans=3
  nfs:
    path: /var/nfs/share/snippetbox/app
    server: 192.168.178.149
