apiVersion: v1
kind: Service
metadata:
  name: sb-app-svc
  namespace: snippetbox
spec:
  ports:
    - port: 8500 # Service port (external access)
      protocol: TCP
      targetPort: 4000 # Pod port (your Go application)
  selector:
    app: sb-app # This should match the labels on your sb-app
  type: LoadBalancer
