apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sb-app
  name: sb-app
  namespace: snippetbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-app
  template:
    metadata:
      labels:
        app: sb-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - image: ghcr.io/gburgers/snippetbox:v0.8.0
          name: sb-app
          env:
            - name: DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: DATABASE_DSN
          # volumeMounts:
          # - name: nfs
          # mountPath: /nfs/app
      # volumes:
      # - name: nfs
      # persistentVolumeClaim:
      # claimName: sb-app-pvc
