apiVersion: v1
kind: PersistentVolume
metadata:
  name: sb-db-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    # - nfsvers=3 # Try NFSv3 instead of 4.1
    - hard
    - timeo=600
    - retrans=3
  nfs:
    path: /var/nfs/share/snippetbox/db
    server: 192.168.178.149
