apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-db
spec:
  selector:
    matchLabels:
      app: sb-db
  template:
    metadata:
      labels:
        app: sb-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          volumeMounts:
            - name: nfs
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: MYSQL_DATABASE
              value: "snippetbox"
          ports:
            - containerPort: 3306
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: sb-db-pvc
