name: Build and Push

on:
  push:
    # branches: [main]
    tags:
      - "v*" # This will trigger the workflow when tags starting with 'v' are pushed
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Debug directory structure
        run: find . -type d | sort

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}      # Gives you v0.0.9
            type=semver,pattern={{version}}  # Gives you 0.0.9
            type=semver,pattern={{major}}.{{minor}}  # Gives you 0.0
            type=semver,pattern={{major}}    # Gives you 0
            type=sha                         # Gives you sha-b086687

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
